<?php
$e=static fn($value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$portalRole='ADMIN';
$portalActive='configuration';
require __DIR__.'/partials/portal-context.php';
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $e($title) ?> | Politeknik Aceh</title><link rel="stylesheet" href="/assets/app.css"></head><body class="portal-body"><div class="portal-shell" data-dashboard-role="ADMIN">
<?php require __DIR__.'/partials/portal-sidebar.php'; ?>
<main id="main-content" tabindex="-1" class="portal-main portal-workspace configuration-workspace">
<header class="portal-toolbar portal-page-toolbar"><div><h1>Konfigurasi sistem</h1><p>Atur jalur masuk, program studi, gelombang, dan parameter ujian dalam satu ruang kerja.</p></div><div class="portal-toolbar-actions"><span class="portal-date">Pengaturan Admin</span></div></header><?php if($adminSuccess):?><div class="alert success-alert" role="status"><?= $e($adminSuccess) ?></div><?php endif;?><?php if($adminError):?><div class="alert error" role="alert"><?= $e($adminError) ?></div><?php endif;?>
<section class="admin-grid configuration-grid">
  <div class="configuration-column">
    <article class="portal-panel configuration-program-panel"><h2>Kelola program studi</h2><p class="panel-description">Program aktif tersedia pada form peserta dan template impor XLSX.</p><div class="config-list"><?php foreach($catalog['programs'] as $program):?><details class="program-config"><summary><span><b><?= $e($program['name']) ?></b><small>Kode <?= $e($program['code']) ?></small></span><span class="status-pill status-<?= $program['is_active']?'success':'neutral' ?>"><?= $program['is_active']?'Aktif':'Nonaktif' ?></span></summary><form class="stack inset-form" method="post" action="/admin/program/perbarui"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="program_id" value="<?= $e($program['id']) ?>"><div class="grid no-margin"><label>Kode<input name="code" value="<?= $e($program['code']) ?>" required></label><label>Nama program<input name="name" value="<?= $e($program['name']) ?>" required></label></div><button class="primary">Simpan</button></form><div class="actions"><form method="post" action="/admin/status"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="entity" value="program"><input type="hidden" name="id" value="<?= $e($program['id']) ?>"><button class="quiet-button"><?= $program['is_active']?'Nonaktifkan':'Aktifkan' ?></button></form><form method="post" action="/admin/program/hapus" onsubmit="return confirm('Hapus program ini?');"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="program_id" value="<?= $e($program['id']) ?>"><button class="quiet-button danger-button">Hapus</button></form></div></details><?php endforeach;?></div><form class="stack inset-form" method="post" action="/admin/program"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label>Kode program<input name="code" placeholder="Contoh: TI" required></label><label>Nama program<input name="name" placeholder="Teknologi Informasi" required></label><button class="primary">Tambah program</button></form></article>
    <article class="portal-panel configuration-wave-panel"><h2>Buat gelombang ujian</h2><form class="stack" method="post" action="/admin/gelombang"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><div class="grid no-margin"><label>Kode<input name="code" placeholder="GEL-2-2026" required></label><label>Nama<input name="name" placeholder="Gelombang 2" required></label></div><div class="grid no-margin"><label>Jumlah soal<input name="exam_question_count" inputmode="numeric" value="20" required></label><label>Durasi menit<input name="exam_duration_minutes" inputmode="numeric" value="30" required></label><label>Passing grade<input name="passing_grade" inputmode="decimal" value="60" required></label></div><label>Mode keamanan<select name="security_mode"><option value="PROCTORING_LITE">Web strict dan proctoring lite</option><option value="WEB_STRICT">Web strict</option></select></label><button class="primary">Buat gelombang</button></form></article>
  </div>
  <article class="portal-panel configuration-path-panel"><h2>Kelola jalur masuk</h2><p class="panel-description">Jalur aktif tersedia pada form peserta dan template impor XLSX.</p><div class="config-list"><?php foreach($catalog['admission_paths'] as $admissionPath):?><details class="path-config"><summary><span><b><?= $e($admissionPath['name']) ?></b><small><?= $admissionPath['is_active']?'Tersedia untuk peserta baru':'Tidak tersedia untuk peserta baru' ?></small></span><span class="status-pill status-<?= $admissionPath['is_active']?'success':'neutral' ?>"><?= $admissionPath['is_active']?'Aktif':'Nonaktif' ?></span></summary><form class="stack inset-form" method="post" action="/admin/jalur-masuk/perbarui"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="admission_path_id" value="<?= $e($admissionPath['id']) ?>"><label>Nama jalur masuk<input name="name" maxlength="64" value="<?= $e($admissionPath['name']) ?>" required></label><button class="primary">Simpan</button></form><div class="actions"><form method="post" action="/admin/status"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="entity" value="admission_path"><input type="hidden" name="id" value="<?= $e($admissionPath['id']) ?>"><button class="quiet-button"><?= $admissionPath['is_active']?'Nonaktifkan':'Aktifkan' ?></button></form><form method="post" action="/admin/jalur-masuk/hapus" onsubmit="return confirm('Hapus jalur masuk ini? Jalur yang sudah dipakai peserta tidak dapat dihapus.');"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="admission_path_id" value="<?= $e($admissionPath['id']) ?>"><button class="quiet-button danger-button">Hapus</button></form></div></details><?php endforeach;?></div><form class="stack inset-form" method="post" action="/admin/jalur-masuk"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label>Nama jalur masuk<input name="name" maxlength="64" placeholder="Contoh: Jalur Mandiri" required></label><button class="primary">Tambah jalur</button></form></article>
</section>
<section class="portal-panel"><h2>Gelombang tersimpan</h2><?php foreach($catalog['waves'] as $wave):?><details class="wave-config"><summary><span><b><?= $e($wave['name']) ?></b><small><?= $e($wave['code']) ?> | <?= $e($wave['exam_question_count']) ?> soal | <?= $e($wave['exam_duration_minutes']) ?> menit</small></span><span class="status-pill status-<?= $wave['is_active']?'success':'neutral' ?>"><?= $wave['is_active']?'Aktif':'Nonaktif' ?></span></summary><div class="wave-actions"><form method="post" action="/admin/status"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="entity" value="wave"><input type="hidden" name="id" value="<?= $e($wave['id']) ?>"><button class="quiet-button"><?= $wave['is_active']?'Nonaktifkan':'Aktifkan' ?></button></form></div><form class="stack inset-form" method="post" action="/admin/gelombang/perbarui"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="wave_id" value="<?= $e($wave['id']) ?>"><div class="grid no-margin"><label>Kode<input name="code" value="<?= $e($wave['code']) ?>" required></label><label>Nama<input name="name" value="<?= $e($wave['name']) ?>" required></label></div><div class="grid no-margin"><label>Jumlah soal<input name="exam_question_count" value="<?= $e($wave['exam_question_count']) ?>" required></label><label>Durasi menit<input name="exam_duration_minutes" value="<?= $e($wave['exam_duration_minutes']) ?>" required></label><label>Passing grade<input name="passing_grade" value="<?= $e($wave['passing_grade']) ?>" required></label></div><label>Mode keamanan<select name="security_mode"><option value="PROCTORING_LITE" <?= $wave['security_mode']==='PROCTORING_LITE'?'selected':'' ?>>Web strict dan proctoring lite</option><option value="WEB_STRICT" <?= $wave['security_mode']==='WEB_STRICT'?'selected':'' ?>>Web strict</option></select></label><button class="primary">Simpan konfigurasi</button></form></details><?php endforeach;?></section>
</main></div></body></html>
