<?php
$e=static fn($value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$labels=['PENDING'=>'Menunggu','APPROVED'=>'Disetujui','NEEDS_CORRECTION'=>'Perlu perbaikan','REJECTED'=>'Ditolak'];
$tones=['PENDING'=>'info','APPROVED'=>'success','NEEDS_CORRECTION'=>'warning','REJECTED'=>'danger'];
$admissionPaths=$participantData['admissionPaths'];
$portalRole='ADMIN';
$portalActive='participants';
require __DIR__.'/partials/portal-context.php';
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $e($title) ?> | Politeknik Aceh</title><link rel="stylesheet" href="/assets/app.css"></head><body class="portal-body participants-page-body"><div class="portal-shell" data-dashboard-role="ADMIN">
<?php require __DIR__.'/partials/portal-sidebar.php'; ?>
<main id="main-content" tabindex="-1" class="portal-main portal-workspace participants-workspace">
<header class="portal-toolbar portal-page-toolbar"><div><h1>Kelola peserta</h1><p>Tambah, cari, dan periksa akun peserta dari satu ruang kerja.</p></div><div class="portal-toolbar-actions"><span class="portal-date"><?= $e($participantData['paginator']->total) ?> peserta</span></div></header>
<?php if($participantSuccess):?><div class="alert success-alert" role="status"><?= $e($participantSuccess) ?></div><?php endif;?><?php if($participantError):?><div class="alert error" role="alert"><?= $e($participantError) ?></div><?php endif;?>
<?php if($participantCredential):?><section class="card compact" aria-labelledby="participant-password-title"><h2 id="participant-password-title">Password peserta</h2><p>Nomor peserta: <code><?= $e($participantCredential['number']) ?></code></p><p>Password: <code><?= $e($participantCredential['password']) ?></code></p><p class="form-footnote">Tampilan ini hanya tersedia sampai halaman dimuat ulang. Setiap pembukaan password dicatat pada audit log.</p></section><?php endif;?>
<?php if($participantImport):?><section class="card compact import-result"><h2>Hasil impor</h2><?php if($participantImport['credentials']):?><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Nomor peserta</th><th>Password awal</th></tr></thead><tbody><?php foreach($participantImport['credentials'] as $credential):?><tr><td><?= $e($credential['name']) ?></td><td><code><?= $e($credential['number']) ?></code></td><td><code><?= $e($credential['password']) ?></code></td></tr><?php endforeach;?></tbody></table></div><p class="form-footnote">Kredensial ini dapat dilihat kembali oleh Admin dari daftar peserta.</p><?php endif;?><?php if($participantImport['errors']):?><div class="alert error"><?= $e(implode(' ',$participantImport['errors'])) ?></div><?php endif;?></section><?php endif;?>
<section class="portal-panel participant-management-panel">
  <header class="participant-management-heading"><div><h2>Daftar dan penambahan peserta</h2><p>Form peserta baru mengikuti susunan data pada daftar di bawahnya.</p></div><details class="participant-import"><summary>Impor XLSX</summary><div class="participant-import-content"><div class="participant-import-header"><div><strong>Tambahkan banyak peserta</strong><small>Template memuat petunjuk dan dropdown kode aktif. Maksimal 5 MB atau 2.000 baris.</small></div><a class="quiet-button" href="/admin/peserta/template"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg><span>Unduh template XLSX</span></a></div><form class="participant-import-form" method="post" action="/admin/peserta/impor" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label class="file-picker"><span class="visually-hidden">Berkas peserta</span><span class="file-picker-control"><input class="file-picker-input" data-file-picker type="file" name="participant_file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required><span class="file-picker-surface"><span class="file-picker-button">Pilih XLSX</span><span class="file-picker-name" data-file-name>Belum ada berkas dipilih</span></span></span></label><button class="primary" type="submit">Impor</button></form></div></details></header>

  <form class="participant-entry-form" method="post" action="/admin/peserta">
    <input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>">
    <label class="col-name">Nama lengkap<input name="full_name" maxlength="160" required></label>
    <label class="col-email">Email<input type="email" name="email" maxlength="190" required></label>
    <label class="col-phone">Nomor telepon<input name="phone_number" maxlength="32" required></label>
    <label class="col-school">Asal sekolah<input name="school_name" maxlength="190" required></label>
    <label class="col-year">Tahun lulus<input name="graduation_year" inputmode="numeric" required></label>
    <label class="col-path">Jalur masuk<select name="admission_path" required><option value=""><?= $admissionPaths ? 'Pilih jalur' : 'Belum ada jalur aktif' ?></option><?php foreach($admissionPaths as $path):?><option value="<?= $e($path) ?>"><?= $e($path) ?></option><?php endforeach;?></select></label>
    <label class="col-program">Program studi<select name="program_id" required><option value="">Pilih program</option><?php foreach($participantData['programs'] as $program):?><option value="<?= $e($program['id']) ?>"><?= $e($program['code'].' | '.$program['name']) ?></option><?php endforeach;?></select></label>
    <label class="col-wave">Gelombang<select name="wave_id" required><option value="">Pilih gelombang</option><?php foreach($participantData['waves'] as $wave):?><option value="<?= $e($wave['id']) ?>"><?= $e($wave['code'].' | '.$wave['name']) ?></option><?php endforeach;?></select></label>
    <label class="col-user">Username <span>(opsional)</span><input name="username" minlength="4" maxlength="32" placeholder="Dibuat otomatis jika kosong"></label>
    <button class="primary col-submit">Tambah peserta</button>
  </form>

  <form class="participant-filter-bar" method="get" action="/admin/peserta"><label>Cari peserta<input name="search" value="<?= $e($participantFilters['search']) ?>" placeholder="Nama, email, atau nomor peserta"></label><label>Jalur masuk<select name="admission_path" onchange="this.form.submit()"><option value="">Semua jalur masuk</option><?php foreach($admissionPaths as $path):?><option value="<?= $e($path) ?>" <?= ($participantFilters['admission_path'] ?? '') === $path ? 'selected' : '' ?>><?= $e($path) ?></option><?php endforeach;?></select></label><label>Status<select name="status" onchange="this.form.submit()"><option value="ALL">Semua status</option><?php foreach($labels as $value=>$label):?><option value="<?= $e($value) ?>" <?= $participantFilters['status']===$value?'selected':'' ?>><?= $e($label) ?></option><?php endforeach;?></select></label><?php if($participantFilters['search']!==''||$participantFilters['status']!=='ALL'||($participantFilters['admission_path'] ?? '')!==''):?><a class="quiet-button" href="/admin/peserta" style="align-self: flex-end; margin-bottom: 2px;">Reset filter</a><?php endif;?></form>

  <div class="participant-table-region"><table class="participant-table"><thead><tr><th>Nomor peserta</th><th>Peserta</th><th>Kontak</th><th>Asal sekolah</th><th>Jalur masuk</th><th>Program studi</th><th>Gelombang</th><th>Status</th><th>Password</th></tr></thead><tbody><?php foreach($participantData['participants'] as $row):?><tr><td><code><?= $e($row['registration_number']) ?></code></td><td><b><?= $e($row['full_name']) ?></b></td><td><?= $e($row['email']) ?><small><?= $e($row['phone_number'] ?? '') ?></small></td><td><?= $e($row['school_name']) ?><small><?= $e($row['graduation_year'] ?? '') ?></small></td><td><?= $e($row['admission_path']) ?></td><td><?= $e($row['program_choice']) ?></td><td><?= $e($row['wave']) ?></td><td><span class="status-pill status-<?= $e($tones[$row['verification_status']]??'neutral') ?>"><?= $e($labels[$row['verification_status']]??$row['verification_status']) ?></span></td><td><form method="post" action="/admin/peserta/password"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="participant_id" value="<?= $e($row['id']) ?>"><button class="quiet-button" type="submit">Lihat password</button></form></td></tr><?php endforeach;?></tbody></table><?php if(!$participantData['participants']):?><div class="table-empty"><b>Belum ada peserta</b><span>Isi baris penambahan di atas atau gunakan impor XLSX.</span></div><?php endif;?></div>
  <?= $participantData['paginator']->links('/admin/peserta',['search'=>$participantFilters['search'],'status'=>$participantFilters['status'],'admission_path'=>$participantFilters['admission_path']??'']) ?>
</section>
</main></div><script src="/assets/file-picker.js" defer></script></body></html>
