<?php
$e=static fn($value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$portalRole='ADMIN';
$portalActive='questions';
require __DIR__.'/partials/portal-context.php';
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $e($title) ?> | Politeknik Aceh</title><link rel="stylesheet" href="/assets/app.css"></head><body class="portal-body"><div class="portal-shell" data-dashboard-role="ADMIN">
<?php require __DIR__.'/partials/portal-sidebar.php'; ?>
<main id="main-content" tabindex="-1" class="portal-main portal-workspace question-studio">
<header class="portal-toolbar portal-page-toolbar"><div><h1>Bank soal</h1><p>Kelola kategori, soal, kunci jawaban, status aktif, dan impor file dalam satu ruang kerja.</p></div><div class="portal-toolbar-actions"><a class="quiet-button" href="/admin/ujian">Buka sesi ujian</a></div></header>
<?php if($adminSuccess):?><div class="alert success-alert" role="status"><?= $e($adminSuccess) ?></div><?php endif;?><?php if($adminError):?><div class="alert error" role="alert"><?= $e($adminError) ?></div><?php endif;?>

<section class="admin-grid question-tools"><article class="card compact"><h2>Tambah kategori soal</h2><form class="stack" method="post" action="/admin/kategori"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label>Kode kategori<input name="code" maxlength="24" placeholder="Contoh: TPA" required></label><label>Nama kategori<input name="name" maxlength="100" placeholder="Tes Potensi Akademik" required></label><button class="primary">Tambah kategori</button></form><div class="tag-list"><?php foreach($questionBank['categories'] as $category):?><span><?= $e($category['code'].' | '.$category['name']) ?></span><?php endforeach;?></div></article>
<article class="card compact"><h2>Impor soal XLSX</h2><p class="intro">Template memuat petunjuk dan dropdown kode aktif. Satu baris gagal membuat seluruh file dibatalkan. Duplikat dalam file dan bank aktif akan ditolak.</p><a class="quiet-button" href="/admin/bank-soal/template">Unduh template XLSX</a><form class="stack upload-form" method="post" action="/admin/bank-soal/impor" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label class="file-picker"><span>Berkas soal</span><span class="file-picker-control"><input class="file-picker-input" data-file-picker type="file" name="question_file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required><span class="file-picker-surface"><span class="file-picker-button">Pilih XLSX</span><span class="file-picker-name" data-file-name>Belum ada berkas dipilih</span></span></span><small>Maksimal 5 MB atau 2.000 baris.</small></label><button class="primary">Validasi dan impor</button></form></article></section>

<section class="portal-panel question-create"><h2>Tambah soal pilihan ganda</h2><form class="stack" method="post" action="/admin/soal"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><label>Kategori<select name="category_id" required><option value="">Pilih kategori</option><?php foreach($questionBank['categories'] as $category):?><option value="<?= $e($category['id']) ?>"><?= $e($category['name']) ?></option><?php endforeach;?></select></label><label>Pertanyaan<textarea name="question_text" required></textarea></label><div class="option-field-grid"><label>Opsi A<input name="option_a" required></label><label>Opsi B<input name="option_b" required></label><label>Opsi C<input name="option_c" required></label><label>Opsi D<input name="option_d" required></label></div><label class="answer-key-field">Kunci jawaban<select name="correct_option"><option>A</option><option>B</option><option>C</option><option>D</option></select></label><button class="primary">Simpan soal</button></form></section>

<section class="portal-panel question-bank-filter"><form class="filter-row" method="get" action="/admin/bank-soal"><label>Cari soal atau opsi<input name="search" value="<?= $e($questionBankFilters['search']) ?>" placeholder="Ketik kata kunci"></label><label>Kategori<select name="category_id"><option value="">Semua kategori</option><?php foreach($questionBank['categories'] as $category):?><option value="<?= $e($category['id']) ?>" <?= $questionBankFilters['category_id']===$category['id']?'selected':'' ?>><?= $e($category['name']) ?></option><?php endforeach;?></select></label><label>Status<select name="status"><option value="ACTIVE" <?= $questionBankFilters['status']==='ACTIVE'?'selected':'' ?>>Aktif</option><option value="INACTIVE" <?= $questionBankFilters['status']==='INACTIVE'?'selected':'' ?>>Tidak aktif</option><option value="ALL" <?= $questionBankFilters['status']==='ALL'?'selected':'' ?>>Semua</option></select></label><button class="primary">Terapkan</button><a class="quiet-button" href="/admin/bank-soal">Reset</a></form></section>

<section class="question-bank-list" aria-label="Daftar soal"><p class="queue-count"><?= $e($questionBank['paginator']->total) ?> soal ditemukan</p><?php foreach($questionBank['questions'] as $index=>$question):?><details class="question-bank-item"><summary><span><b><?= $e((($questionBank['paginator']->page-1)*$questionBank['paginator']->perPage)+$index+1) ?>. <?= $e(mb_strimwidth($question['question_text'],0,130,'...')) ?></b><small><?= $e($question['category_name']) ?></small></span><span class="status-pill status-<?= (int)$question['is_active']===1?'success':'neutral' ?>"><?= (int)$question['is_active']===1?'Aktif':'Tidak aktif' ?></span></summary>
<?php if((int)$question['is_active']===1):?><form class="stack inset-form" method="post" action="/admin/soal/perbarui"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="question_id" value="<?= $e($question['id']) ?>"><label>Kategori<select name="category_id" required><?php foreach($questionBank['categories'] as $category):?><option value="<?= $e($category['id']) ?>" <?= $question['category_id']===$category['id']?'selected':'' ?>><?= $e($category['name']) ?></option><?php endforeach;?></select></label><label>Pertanyaan<textarea name="question_text" required><?= $e($question['question_text']) ?></textarea></label><div class="option-field-grid"><label>Opsi A<input name="option_a" value="<?= $e($question['option_a']) ?>" required></label><label>Opsi B<input name="option_b" value="<?= $e($question['option_b']) ?>" required></label><label>Opsi C<input name="option_c" value="<?= $e($question['option_c']) ?>" required></label><label>Opsi D<input name="option_d" value="<?= $e($question['option_d']) ?>" required></label></div><label class="answer-key-field">Kunci jawaban<select name="correct_option"><?php foreach(['A','B','C','D'] as $option):?><option value="<?= $option ?>" <?= $question['correct_option']===$option?'selected':'' ?>><?= $option ?></option><?php endforeach;?></select></label><button class="primary">Simpan perubahan</button></form><form class="delete-form" method="post" action="/admin/soal/nonaktifkan" onsubmit="return confirm('Nonaktifkan soal ini?');"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="question_id" value="<?= $e($question['id']) ?>"><button class="quiet-button danger-button">Nonaktifkan</button></form><?php else:?><div class="inset-form"><p>Soal disimpan sebagai riwayat dan tidak dipilih untuk ujian baru.</p><form method="post" action="/admin/soal/aktifkan"><input type="hidden" name="csrf" value="<?= $e($_SESSION['csrf']) ?>"><input type="hidden" name="question_id" value="<?= $e($question['id']) ?>"><button class="quiet-button">Aktifkan kembali</button></form></div><?php endif;?></details><?php endforeach;?><?php if(!$questionBank['questions']):?><article class="portal-panel table-empty"><b>Tidak ada soal</b><span>Ubah filter atau tambahkan soal baru.</span></article><?php endif;?><?= $questionBank['paginator']->links('/admin/bank-soal',['search'=>$questionBankFilters['search'],'category_id'=>$questionBankFilters['category_id'],'status'=>$questionBankFilters['status']]) ?></section>
</main></div><script src="/assets/file-picker.js" defer></script></body></html>
