<?php
$e = static fn ($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$portalRole = 'PARTICIPANT';
$portalActive = 'exams';
require __DIR__ . '/partials/portal-context.php';
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $e($title) ?> · Politeknik Aceh</title><link rel="stylesheet" href="/assets/app.css"></head><body class="portal-body"><div class="portal-shell" data-dashboard-role="PARTICIPANT">
<?php require __DIR__ . '/partials/portal-sidebar.php'; ?>
<main id="main-content" tabindex="-1" class="portal-main portal-workspace security-workspace"><header class="portal-toolbar portal-page-toolbar"><div><h1>Pemeriksaan perangkat</h1><p>Selesaikan kamera dan layar penuh sebelum timer ujian dimulai.</p></div><div class="portal-toolbar-actions"><a class="quiet-button" href="/ujian">Kembali ke sesi</a></div></header><section class="portal-panel security-panel"><div class="security-copy"><h2>Siapkan perangkat Anda</h2><p>Izinkan kamera, masuk layar penuh, lalu ambil satu foto awal. Foto disimpan privat dan hanya dapat dibuka Admin melalui menu Pengawasan.</p><ul class="security-checklist"><li><svg class="check-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="M4.5 10.4 8.2 14l7.3-8"/></svg><span>Kamera aktif dan wajah terlihat jelas</span></li><li><svg class="check-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="M4.5 10.4 8.2 14l7.3-8"/></svg><span>Browser berada dalam mode layar penuh</span></li><li><svg class="check-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="M4.5 10.4 8.2 14l7.3-8"/></svg><span>Koneksi internet stabil selama ujian</span></li></ul><div id="security-status" class="alert notice" role="status">Menunggu izin kamera.</div><div class="actions"><button class="primary" id="prepare" type="button">Periksa kamera dan lanjutkan</button></div></div><video id="camera" class="camera-preview" autoplay muted playsinline></video><canvas id="canvas" hidden></canvas></section></main></div><script>
const csrf=<?= json_encode($_SESSION['csrf']) ?>,attemptId=<?= json_encode($attempt['id']) ?>,status=document.getElementById('security-status'),video=document.getElementById('camera'),canvas=document.getElementById('canvas');
async function event(type){try{const body=new URLSearchParams({csrf,attempt_id:attemptId,event_type:type});const response=await fetch('/ujian/security/event',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await response.json();if(data.paused)status.textContent='Attempt dihentikan untuk review Admin.';}catch{}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)event('TAB_HIDDEN')});document.addEventListener('fullscreenchange',()=>event(document.fullscreenElement?'FULLSCREEN_ENTERED':'FULLSCREEN_EXIT'));
document.getElementById('prepare').addEventListener('click',async()=>{let stream=null;try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen({navigationUI:'hide'});stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});video.srcObject=stream;await event('CAMERA_GRANTED');await new Promise(resolve=>setTimeout(resolve,500));canvas.width=video.videoWidth||640;canvas.height=video.videoHeight||480;canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);status.textContent='Mengirim foto awal…';const body=new URLSearchParams({csrf,attempt_id:attemptId,photo:canvas.toDataURL('image/jpeg',.75)});const response=await fetch('/ujian/security/photo',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await response.json();if(!data.ok)throw new Error(data.message);stream.getTracks().forEach(track=>track.stop());location.href='/ujian/ruang?attempt='+encodeURIComponent(attemptId);}catch(error){if(stream)stream.getTracks().forEach(track=>track.stop());await event('CAMERA_DENIED');status.textContent='Kamera atau layar penuh belum tersedia. Periksa izin perangkat atau hubungi Panitia.';}});
</script></body></html>
